### ISSUE TITLE
Unused token section appearing as tab and out-of-place token annotations

### ISSUE THREAD

**Issue by Smolations** [UX-and-I/storybook-design-token#52]
Hello again! 😁 

So I _finally_ got around to doing some storybook upgrades and am currently pointing at the most recent version (6.3.2) so it seemed logical to upgrade your addon as well, since I was previously on 0.x.x. Nice to see the new layouts and features! I have two issues though, and I'm happy to open a second issue if needed, but the most pressing issue is this empty tab:

<img width="907" alt="Screen Shot 2021-07-01 at 7 19 57 PM" src="https://user-images.githubusercontent.com/952681/124206824-55435d00-daa1-11eb-9e81-ef5dba98553b.png">

I never once reference an svg presenter in my comment annotations, nor are there any sass variables (tokens) which represent svgs. I _do_ have some svg's in the app, but we use FontAwesome packages for their display, so we have no need to list them as tokens. I'm not sure why this tab is appearing.

The second issue is that individual token annotations (line-level comments) seem to be getting mixed up and/or pulled randomly, while others display just fine (btw, the tooltip-style of delivery is convenient!). Here is an example from my `_colors.scss` file:
```scss
/**
 * @tokens Colors
 * @presenter Color
 *
 * NOTE: legacy color files are in styles/components/Color. when there
 *       are multiple colors listed, they are located in multiple files.
 *       commented colors are generally included when names drastically
 *       differ, but some are listed for convenience as well. may be
 *       helpful to simply list _all_ defined stylus vars to use as a
 *       complete reference.
 */

// primary palette
$purple: #723080; // formerly purple
$purple-tint-1: #f1e9ef;
$purple-tint-2: #d4c0d7;
$purple-tint-3: #b897bf; // formerly color-p-tint-1 (colors.js)
$purple-tint-4: #8e5999; // formerly color-p-tint-2 (colors.js)
$purple-shade-1: #5b2666;
$purple-shade-2: #441c4c;
$purple-shade-3: #2d1631;
```

Observe the tooltips:
![storybook-design-token_annotations](https://user-images.githubusercontent.com/952681/124207391-a869df80-daa2-11eb-8eda-4f80f7595e26.gif)

Only one of the tooltips was correct, and the others seem to be coming from other files. I suspect it's a small react snafu, but a snafu nonetheless. Again, let me know if you'd prefer this to be in a separate issue. 😅

**Comment by Sqrrl** [comment]
Thanks for reporting. Should both be fixed with v1.1.1

**Comment by Smolations** [comment]
Holy crap @Sqrrl you're a beast!  But I just pulled down the new update and both issues still persist. Is there a way I can enable any debugging information so I can provide you with additional info?

**Comment by Sqrrl** [comment]
I though I was able to reproduce your issues. Could you check your yarn.lock/package-lock.json and check that you have v1.1.1 installed?

I will check the issues again.

**Comment by Smolations** [comment]
@Sqrrl I did check the lock file and it had the updated version, but something must have been off on my end. I removed node_modules and reinstalled and now it appears both issues are fixed. Killer response time, thanks!  👏 👏 👏
